before_script:
  - dmenv install

variables:
  SDK_NATIVE_COMMIT_HASH: '9105d10ba426f88577ea1fd11ab1331ebc4f16eb'

stages:
  - build
  - deploy

build/linux:
  stage: build
  tags:
    - linux
  script:
    - dmenv run -- python run-ci.py clean-conan-cache
    - dmenv run -- python run-ci.py deploy --profile gcc8 --profile android --build-only --ref ${CI_COMMIT_REF_NAME}

build/macos:
  stage: build
  tags:
    - macos
  script:
    - dmenv run -- python run-ci.py clean-conan-cache
    - dmenv run -- python run-ci.py deploy --profile macos --profile ios --build-only --ref ${CI_COMMIT_REF_NAME}

deploy/linux:
  stage: deploy
  tags:
    - linux
  when: manual
  script:
    - dmenv run -- python run-ci.py clean-conan-cache
    - dmenv run -- python run-ci.py deploy --profile gcc8 --profile android --ref ${CI_COMMIT_REF_NAME} --native-commit-hash ${SDK_NATIVE_COMMIT_HASH}


deploy/macos:
  stage: deploy
  tags:
    - macos
  when: manual
  script:
    - dmenv run -- python run-ci.py clean-conan-cache
    - dmenv run -- python run-ci.py deploy --profile macos --profile ios --ref ${CI_COMMIT_REF_NAME} --native-commit-hash ${SDK_NATIVE_COMMIT_HASH}
