image: tanker.local:5000/ci-cpp:latest

before_script:
  - dmenv install

stages:
  - build
  - deploy

.build:
  stage: build
  except:
    - /\Atesting/.*\z/
    - /\Astable/.*\z/

build/linux:
  extends: .build
  tags: [linux]
  script:
    - dmenv run -- python run-ci.py build

build/macos:
  extends: .build
  tags: [macos]
  script:
    - dmenv run -- python run-ci.py build

build/windows:
  extends: .build
  tags: [windows]
  script:
    - dmenv run -- python run-ci.py build


.deploy:
  stage: deploy
  only:
    - /\Atesting/.*\z/
    - /\Astable/.*\z/

deploy/linux:
  extends: .deploy
  tags: [linux]
  script:
    - dmenv run -- python run-ci.py deploy

deploy/macos:
  extends: .deploy
  tags: [macos]
  script:
    - dmenv run -- python run-ci.py deploy

deploy/windows:
  extends: .deploy
  tags: [windows]
  script:
    - dmenv run -- python run-ci.py deploy
