before_script:
  - dmenv install

stages:
  - build
  - deploy

build/linux:
  stage: build
  tags:
    - linux
  only:
    - web
  script:
    - dmenv run -- python run-ci.py clean-conan-cache
    - dmenv run -- python run-ci.py deploy --profile android --ref ${CI_COMMIT_REF_NAME}

build/macos:
  stage: build
  only:
    - web
  tags:
    - macos
  script:
    - dmenv run -- python run-ci.py clean-conan-cache
    - dmenv run -- python run-ci.py deploy --profile macos --profile ios --ref ${CI_COMMIT_REF_NAME}
